<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('countries')->delete();

        $countries = [
            ["code" => "AFG", "name" => "Afghanistan"],
            ["code" => "ZAF", "name" => "Afrique du Sud"],
            ["code" => "ALB", "name" => "Albanie"],
            ["code" => "DZA", "name" => "Algérie"],
            ["code" => "DEU", "name" => "Allemagne"],
            ["code" => "AND", "name" => "Andorre"],
            ["code" => "ENG", "name" => "Angleterre"], // Ajout FIFA
            ["code" => "AGO", "name" => "Angola"],
            ["code" => "AIA", "name" => "Anguilla"],
            ["code" => "ATA", "name" => "Antarctique"],
            ["code" => "ATG", "name" => "Antigua-et-Barbuda"],
            ["code" => "SAU", "name" => "Arabie saoudite"],
            ["code" => "ARG", "name" => "Argentine"],
            ["code" => "ARM", "name" => "Arménie"],
            ["code" => "ABW", "name" => "Aruba"],
            ["code" => "AUS", "name" => "Australie"],
            ["code" => "AUT", "name" => "Autriche"],
            ["code" => "AZE", "name" => "Azerbaïdjan"],
            ["code" => "BHS", "name" => "Bahamas"],
            ["code" => "BHR", "name" => "Bahreïn"],
            ["code" => "BGD", "name" => "Bangladesh"],
            ["code" => "BRB", "name" => "Barbade"],
            ["code" => "BEL", "name" => "Belgique"],
            ["code" => "BLZ", "name" => "Belize"],
            ["code" => "BEN", "name" => "Bénin"],
            ["code" => "BMU", "name" => "Bermudes"],
            ["code" => "BTN", "name" => "Bhoutan"],
            ["code" => "BLR", "name" => "Biélorussie"],
            ["code" => "MMR", "name" => "Birmanie"],
            ["code" => "BOL", "name" => "Bolivie"],
            ["code" => "BIH", "name" => "Bosnie-Herzégovine"],
            ["code" => "BWA", "name" => "Botswana"],
            ["code" => "BRA", "name" => "Brésil"],
            ["code" => "BRN", "name" => "Brunéi Darussalam"],
            ["code" => "BGR", "name" => "Bulgarie"],
            ["code" => "BFA", "name" => "Burkina Faso"],
            ["code" => "BDI", "name" => "Burundi"],
            ["code" => "KHM", "name" => "Cambodge"],
            ["code" => "CMR", "name" => "Cameroun"],
            ["code" => "CAN", "name" => "Canada"],
            ["code" => "CPV", "name" => "Cap-Vert"],
            ["code" => "CHL", "name" => "Chili"],
            ["code" => "CHN", "name" => "Chine"],
            ["code" => "CYP", "name" => "Chypre"],
            ["code" => "COL", "name" => "Colombie"],
            ["code" => "COM", "name" => "Comores"],
            ["code" => "COG", "name" => "Congo-Brazzaville"],
            ["code" => "COD", "name" => "Congo-Kinshasa"],
            ["code" => "PRK", "name" => "Corée du Nord"],
            ["code" => "KOR", "name" => "Corée du Sud"],
            ["code" => "CRI", "name" => "Costa Rica"],
            ["code" => "CIV", "name" => "Côte d’Ivoire"],
            ["code" => "HRV", "name" => "Croatie"],
            ["code" => "CUB", "name" => "Cuba"],
            ["code" => "CUW", "name" => "Curaçao"],
            ["code" => "DNK", "name" => "Danemark"],
            ["code" => "DJI", "name" => "Djibouti"],
            ["code" => "DMA", "name" => "Dominique"],
            ["code" => "SCO", "name" => "Écosse"], // Ajout FIFA
            ["code" => "EGY", "name" => "Égypte"],
            ["code" => "ARE", "name" => "Émirats arabes unis"],
            ["code" => "ECU", "name" => "Équateur"],
            ["code" => "ERI", "name" => "Érythrée"],
            ["code" => "ESP", "name" => "Espagne"],
            ["code" => "EST", "name" => "Estonie"],
            ["code" => "SWZ", "name" => "Eswatini"],
            ["code" => "USA", "name" => "États-Unis"],
            ["code" => "ETH", "name" => "Éthiopie"],
            ["code" => "FJI", "name" => "Fidji"],
            ["code" => "FIN", "name" => "Finlande"],
            ["code" => "FRA", "name" => "France"],
            ["code" => "GAB", "name" => "Gabon"],
            ["code" => "GMB", "name" => "Gambie"],
            ["code" => "GEO", "name" => "Géorgie"],
            ["code" => "GHA", "name" => "Ghana"],
            ["code" => "GIB", "name" => "Gibraltar"],
            ["code" => "GRC", "name" => "Grèce"],
            ["code" => "GRD", "name" => "Grenade"],
            ["code" => "GRL", "name" => "Groenland"],
            ["code" => "GLP", "name" => "Guadeloupe"],
            ["code" => "GUM", "name" => "Guam"],
            ["code" => "GTM", "name" => "Guatemala"],
            ["code" => "GGY", "name" => "Guernesey"],
            ["code" => "GIN", "name" => "Guinée"],
            ["code" => "GNB", "name" => "Guinée-Bissau"],
            ["code" => "GNQ", "name" => "Guinée équatoriale"],
            ["code" => "GUY", "name" => "Guyana"],
            ["code" => "GUF", "name" => "Guyane française"],
            ["code" => "HTI", "name" => "Haïti"],
            ["code" => "HND", "name" => "Honduras"],
            ["code" => "HKG", "name" => "Hong Kong"],
            ["code" => "HUN", "name" => "Hongrie"],
            ["code" => "IMN", "name" => "Île de Man"],
            ["code" => "CXR", "name" => "Île Christmas"],
            ["code" => "NFK", "name" => "Île Norfolk"],
            ["code" => "ALA", "name" => "Îles Åland"],
            ["code" => "CYM", "name" => "Îles Caïmans"],
            ["code" => "CCK", "name" => "Îles Cocos"],
            ["code" => "COK", "name" => "Îles Cook"],
            ["code" => "FRO", "name" => "Îles Féroé"],
            ["code" => "FLK", "name" => "Îles Malouines"],
            ["code" => "MNP", "name" => "Îles Mariannes du Nord"],
            ["code" => "MHL", "name" => "Îles Marshall"],
            ["code" => "SLB", "name" => "Îles Salomon"],
            ["code" => "TCA", "name" => "Îles Turques-et-Caïques"],
            ["code" => "VGB", "name" => "Îles Vierges britanniques"],
            ["code" => "VIR", "name" => "Îles Vierges des États-Unis"],
            ["code" => "IND", "name" => "Inde"],
            ["code" => "IDN", "name" => "Indonésie"],
            ["code" => "IRQ", "name" => "Irak"],
            ["code" => "IRN", "name" => "Iran"],
            ["code" => "IRL", "name" => "Irlande"],
            ["code" => "NIR", "name" => "Irlande du Nord"], // Ajout FIFA
            ["code" => "ISL", "name" => "Islande"],
            ["code" => "ISR", "name" => "Israël"],
            ["code" => "ITA", "name" => "Italie"],
            ["code" => "JAM", "name" => "Jamaïque"],
            ["code" => "JPN", "name" => "Japon"],
            ["code" => "JEY", "name" => "Jersey"],
            ["code" => "JOR", "name" => "Jordanie"],
            ["code" => "KAZ", "name" => "Kazakhstan"],
            ["code" => "KEN", "name" => "Kenya"],
            ["code" => "KGZ", "name" => "Kirghizistan"],
            ["code" => "KIR", "name" => "Kiribati"],
            ["code" => "KOS", "name" => "Kosovo"], // Ajout FIFA
            ["code" => "KWT", "name" => "Koweït"],
            ["code" => "LAO", "name" => "Laos"],
            ["code" => "REU", "name" => "La Réunion"],
            ["code" => "LSO", "name" => "Lesotho"],
            ["code" => "LVA", "name" => "Lettonie"],
            ["code" => "LBN", "name" => "Liban"],
            ["code" => "LBR", "name" => "Liberia"],
            ["code" => "LBY", "name" => "Libye"],
            ["code" => "LIE", "name" => "Liechtenstein"],
            ["code" => "LTU", "name" => "Lituanie"],
            ["code" => "LUX", "name" => "Luxembourg"],
            ["code" => "MAC", "name" => "Macao"],
            ["code" => "MKD", "name" => "Macédoine du Nord"],
            ["code" => "MDG", "name" => "Madagascar"],
            ["code" => "MYS", "name" => "Malaisie"],
            ["code" => "MWI", "name" => "Malawi"],
            ["code" => "MDV", "name" => "Maldives"],
            ["code" => "MLI", "name" => "Mali"],
            ["code" => "MLT", "name" => "Malte"],
            ["code" => "MAR", "name" => "Maroc"],
            ["code" => "MTQ", "name" => "Martinique"],
            ["code" => "MUS", "name" => "Maurice"],
            ["code" => "MRT", "name" => "Mauritanie"],
            ["code" => "MYT", "name" => "Mayotte"],
            ["code" => "MEX", "name" => "Mexique"],
            ["code" => "FSM", "name" => "Micronésie"],
            ["code" => "MDA", "name" => "Moldavie"],
            ["code" => "MCO", "name" => "Monaco"],
            ["code" => "MNG", "name" => "Mongolie"],
            ["code" => "MNE", "name" => "Monténégro"],
            ["code" => "MSR", "name" => "Montserrat"],
            ["code" => "MOZ", "name" => "Mozambique"],
            ["code" => "NAM", "name" => "Namibie"],
            ["code" => "NRU", "name" => "Nauru"],
            ["code" => "NPL", "name" => "Népal"],
            ["code" => "NIC", "name" => "Nicaragua"],
            ["code" => "NER", "name" => "Niger"],
            ["code" => "NGA", "name" => "Nigeria"],
            ["code" => "NIU", "name" => "Niue"],
            ["code" => "NOR", "name" => "Norvège"],
            ["code" => "NCL", "name" => "Nouvelle-Calédonie"],
            ["code" => "NZL", "name" => "Nouvelle-Zélande"],
            ["code" => "OMN", "name" => "Oman"],
            ["code" => "UGA", "name" => "Ouganda"],
            ["code" => "UZB", "name" => "Ouzbékistan"],
            ["code" => "PAK", "name" => "Pakistan"],
            ["code" => "PLW", "name" => "Palaos"],
            ["code" => "PSE", "name" => "Palestine"],
            ["code" => "PAN", "name" => "Panama"],
            ["code" => "PNG", "name" => "Papouasie-Nouvelle-Guinée"],
            ["code" => "PRY", "name" => "Paraguay"],
            ["code" => "NLD", "name" => "Pays-Bas"],
            ["code" => "WAL", "name" => "Pays de Galles"], // Ajout FIFA
            ["code" => "PER", "name" => "Pérou"],
            ["code" => "PHL", "name" => "Philippines"],
            ["code" => "PCN", "name" => "Pitcairn"],
            ["code" => "POL", "name" => "Pologne"],
            ["code" => "PRI", "name" => "Porto Rico"],
            ["code" => "PRT", "name" => "Portugal"],
            ["code" => "QAT", "name" => "Qatar"],
            ["code" => "CAF", "name" => "République centrafricaine"],
            ["code" => "DOM", "name" => "République dominicaine"],
            ["code" => "CZE", "name" => "République tchèque"],
            ["code" => "ROU", "name" => "Roumanie"],
            ["code" => "GBR", "name" => "Royaume-Uni"],
            ["code" => "RUS", "name" => "Russie"],
            ["code" => "RWA", "name" => "Rwanda"],
            ["code" => "ESH", "name" => "Sahara occidental"],
            ["code" => "BLM", "name" => "Saint-Barthélemy"],
            ["code" => "KNA", "name" => "Saint-Christophe-et-Niévès"],
            ["code" => "SMR", "name" => "Saint-Marin"],
            ["code" => "MAF", "name" => "Saint-Martin"],
            ["code" => "SPM", "name" => "Saint-Pierre-et-Miquelon"],
            ["code" => "VCT", "name" => "Saint-Vincent-et-les-Grenadines"],
            ["code" => "SHN", "name" => "Sainte-Hélène"],
            ["code" => "LCA", "name" => "Sainte-Lucie"],
            ["code" => "WSM", "name" => "Samoa"],
            ["code" => "ASM", "name" => "Samoa américaines"],
            ["code" => "STP", "name" => "Sao Tomé-et-Principe"],
            ["code" => "SEN", "name" => "Sénégal"],
            ["code" => "SRB", "name" => "Serbie"],
            ["code" => "SYC", "name" => "Seychelles"],
            ["code" => "SLE", "name" => "Sierra Leone"],
            ["code" => "SGP", "name" => "Singapour"],
            ["code" => "SXM", "name" => "Sint Maarten"],
            ["code" => "SVK", "name" => "Slovaquie"],
            ["code" => "SVN", "name" => "Slovénie"],
            ["code" => "SOM", "name" => "Somalie"],
            ["code" => "SDN", "name" => "Soudan"],
            ["code" => "SSD", "name" => "Soudan du Sud"],
            ["code" => "LKA", "name" => "Sri Lanka"],
            ["code" => "SWE", "name" => "Suède"],
            ["code" => "CHE", "name" => "Suisse"],
            ["code" => "SUR", "name" => "Suriname"],
            ["code" => "SYR", "name" => "Syrie"],
            ["code" => "TJK", "name" => "Tadjikistan"],
            ["code" => "TAH", "name" => "Tahiti"], // Nom FIFA (ex-Polynésie fr.)
            ["code" => "TPE", "name" => "Taipei chinois"], // Nom FIFA (ex-Taïwan)
            ["code" => "TZA", "name" => "Tanzanie"],
            ["code" => "TCD", "name" => "Tchad"],
            ["code" => "ATF", "name" => "Terres australes françaises"],
            ["code" => "THA", "name" => "Thaïlande"],
            ["code" => "TLS", "name" => "Timor oriental"],
            ["code" => "TGO", "name" => "Togo"],
            ["code" => "TKL", "name" => "Tokelau"],
            ["code" => "TON", "name" => "Tonga"],
            ["code" => "TTO", "name" => "Trinité-et-Tobago"],
            ["code" => "TUN", "name" => "Tunisie"],
            ["code" => "TKM", "name" => "Turkménistan"],
            ["code" => "TUR", "name" => "Turquie"],
            ["code" => "TUV", "name" => "Tuvalu"],
            ["code" => "UKR", "name" => "Ukraine"],
            ["code" => "URY", "name" => "Uruguay"],
            ["code" => "VUT", "name" => "Vanuatu"],
            ["code" => "VAT", "name" => "Vatican"],
            ["code" => "VEN", "name" => "Venezuela"],
            ["code" => "VNM", "name" => "Vietnam"],
            ["code" => "WLF", "name" => "Wallis-et-Futuna"],
            ["code" => "YEM", "name" => "Yémen"],
            ["code" => "ZMB", "name" => "Zambie"],
            ["code" => "ZWE", "name" => "Zimbabwe"],
        ];
        
        DB::table('countries')->insert($countries);
    }
}
